version: "3"

services:
  dev-container:
    build:
      args:
        user: vscode
        uid: 1000
      context: ./
      dockerfile: docker/devcontainer/Dockerfile
    working_dir: /app
    volumes:
      - "./:/app"
