version: "3.7"

services:
  cake-app:
    build:
      args:
        user: cake
        uid: 1000
      context: ./
      dockerfile: ./vendor/maymeow/sail/sdk/8.0/Dockerfile
    # image: ghcr.io/maymeow/cake-notify/cake-notify:latest
    command: bash -c "composer install && php bin/cake.php server -H 0.0.0.0"
    env_file: .env.dev
    working_dir: /var/www/
    networks:
      - cake
    ports:
      - "8765:8765"
    depends_on:
      - cake-db
      - cake-redis
    volumes:
      - ./:/var/www

  cake-db:
    image: postgres:12.4
    networks:
      - cake
    # ports:
    #   - "5432:5432"
    volumes:
      - cake_data:/var/lib/postgresql/data
    env_file: .env.dev

  cake-redis:
    image: "redis:alpine"
    networks:
      - cake
    volumes:
      - cake_redis:/data

  # if you need graphic acces to application database
  adminer:
    image: adminer
    networks:
      - cake
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    networks:
      - cake
    volumes:
      - minio_data:/data
    env_file: .env.dev
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  cake:
    driver: bridge

volumes:
  cake_data:
    driver: local
  minio_data:
    driver: local
  cake_redis:
    driver: local
