version: "3.7"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes_from:
      - app
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - app
      - db
      - redis

  composer:
    image: ghcr.io/maymeow/php/sdk:8.1.6
    user: "1000:1000"
    working_dir: /var/www/
    command:  bash -c "composer install"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www

  app:
    image: ghcr.io/maymeow/php/runtime:8.1.6
    user: "1000:1000"
    env_file: .env
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www

  db:
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - cake_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: "redis:alpine"
    volumes:
      - cake_redis:/data

  # if you need graphic acces to application database
  adminer:
    image: adminer
    ports:
      - "8081:8080"

  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    volumes:
      - minio_data:/data
    env_file: .env
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  cake:
    driver: bridge

volumes:
  cake_data:
    driver: local
  minio_data:
    driver: local
  cake_redis:
    driver: local
