version: "3.7"

services:
  app-dev:
    build:
      args:
        user: cake
        uid: 1000
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/maymeow/cake-notify/cake-notify:latest
    command: bash -c "composer install && php bin/cake.php server -H 0.0.0.0"
    env_file: ../.env.dev
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8765:8765"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ..:/var/www

  postgres:
    image: postgres:12.4
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    volumes:
      - cake_data:/var/lib/postgresql/data
    env_file: ../.env.dev

  redis:
    image: "redis:alpine"
    env_file: ../.env.dev
    # command: >
    #  --requirepass ${REDIS_PASSWORD}

  # if you need graphic acces to application database
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped


  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    restart: unless-stopped
    volumes:
      - minio_data:/data
    env_file: ../.env.dev
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"


volumes:
  cake_data:
  minio_data:
