baseURL = 'https://starter.maymeow.dev/'
languageCode = 'en-us'
title = '🍰 Starter kit for CakePHP apps'

theme = 'simple-hugo'

[params]
  description = 'CkePHP, PostgreSQL, Redis & Minio included'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "News"
    url = "/posts"
    weight = 20

  [[menu.main]]
    name = "Source code"
    url = "https://github.com/MayMeow/cakephp-starter-kit"
    weight = 30